version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql.magento
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: modulo
      MYSQL_PASSWORD: rede
      MYSQL_ROOT_PASSWORD: rede
    networks:
      - modulo-rede
    volumes:
      - .mysql:/var/lib/mysql:z

  magento2:
    image: magento2
    build: .
    container_name: local.magento
    ports:
      - "80:80"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - modulo-rede
    volumes:
      - ./src:/var/www/html/app/code/Rede/Adquirencia:z

networks:
  modulo-rede:
    driver: bridge