version: '3'

services:
  mysql:
    image: mysql:8
    container_name: rede_magento.mdb
    env_file:
      - .env
    networks:
      - modulo-rede
    volumes:
      - ../.data/mysql:/var/lib/mysql:z

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: rede_magento.es
    ports:
      - ${ELASTICSEARCH_PORT:-9200}:9200
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    env_file:
      - .env
    networks:
      - modulo-rede
    volumes:
      - ../.data/elasticsearch/data:/var/lib/elasticsearch:z

  magento2:
    image: magento2
    container_name: rede_magento.http
    ports:
      - "443:443"
    links:
      - mysql
      - elasticsearch
    depends_on:
      - mysql
      - elasticsearch
    env_file:
      - .env
    networks:
      - modulo-rede
    volumes:
      - ./dev-ssl:/etc/dev-ssl:z
      - ../app/code/Rede/Adquirencia:/var/www/html/app/code/Rede/Adquirencia:z
      - ../.data/http/var:/var/www/html/var:z

networks:
  modulo-rede:
    driver: bridge